#!/usr/bin/env python3
"""
Turn koenk/gbc's linear opcode chains into jump tables.

Upstream decodes with a chain of masked compares:

    if      (M(op, 0x00, 0xff)) { ... }
    else if (M(op, 0x01, 0xcf)) { ... }
    ... 69 of them ...

Every emulated instruction walks that chain from the top until something
matches, so a typical opcode costs ~35 mask-compare-branch sequences before any
useful work happens. On the A480 that was the dominant cost of the interpreter.

This script rewrites each chain as

    switch (gb_op_rule[op]) { case 0: { ... } break; case 1: { ... } break; ... }

with gb_op_rule[] precomputed here, so gcc emits a jump table and dispatch
becomes one indexed load and one indirect branch.

The opcode bodies are copied verbatim - this only replaces the dispatch
around them, which is what makes the transformation safe to apply to vendored
code. Run it against a clean checkout of core/cpu.c; it is idempotent-hostile,
so it refuses to run on an already-converted file.

Usage:  python3 tools/gbc_mkdispatch.py modules/gbc/core/cpu.c
"""

import re
import sys

CHAINS = ["cpu_do_cb_instruction", "cpu_do_instruction"]


def find_body(src, fn):
    """Return (start_of_brace, end_of_brace) for the function's body."""
    i = src.index("static void %s(struct gb_state *s) {" % fn)
    j = src.index("{", i)
    depth = 0
    for k in range(j, len(src)):
        if src[k] == "{":
            depth += 1
        elif src[k] == "}":
            depth -= 1
            if depth == 0:
                return j, k
    raise RuntimeError("unbalanced braces in " + fn)


def split_chain(body):
    """
    Split the if/else-if chain at the top level of the extracted body - depth 0
    here, since `body` is the text *inside* the function's braces, so anything
    at depth > 0 is within an opcode body and must not be split on.
    Returns (prelude, [(value, mask, body)], tail).

    `tail` is the trailing `else { ... }` - the unknown-instruction case.
    """
    depth = 0
    entries = []
    prelude_end = None
    i = 0
    tail = None

    pat_if = re.compile(r"\bif\s*\(\s*M\(op,\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*\)\s*\)\s*\{")
    pat_else = re.compile(r"\belse\s*\{")

    while i < len(body):
        c = body[i]
        if c == "{":
            depth += 1
            i += 1
            continue
        if c == "}":
            depth -= 1
            i += 1
            continue

        if depth == 0:
            m = pat_if.match(body, i)
            if m:
                if prelude_end is None:
                    prelude_end = i
                # capture the braced body that follows
                b_open = m.end() - 1
                d = 0
                for k in range(b_open, len(body)):
                    if body[k] == "{":
                        d += 1
                    elif body[k] == "}":
                        d -= 1
                        if d == 0:
                            b_close = k
                            break
                entries.append((int(m.group(1), 16), int(m.group(2), 16),
                                body[b_open + 1:b_close]))
                i = b_close + 1
                continue

            m = pat_else.match(body, i)
            if m and entries:
                b_open = m.end() - 1
                d = 0
                for k in range(b_open, len(body)):
                    if body[k] == "{":
                        d += 1
                    elif body[k] == "}":
                        d -= 1
                        if d == 0:
                            b_close = k
                            break
                tail = body[b_open + 1:b_close]
                i = b_close + 1
                continue

        i += 1

    return body[:prelude_end], entries, tail


def build_table(entries):
    """First-match rule index per opcode; 0xff means no rule matched."""
    table = []
    for op in range(256):
        idx = 0xFF
        for n, (val, mask, _) in enumerate(entries):
            if (op & mask) == val:
                idx = n
                break
        table.append(idx)
    return table


def emit(fn, prelude, entries, tail, table):
    name = "gb_rule_" + fn.replace("cpu_do_", "").replace("_instruction", "")

    out = []
    out.append("/* Dispatch table generated by tools/gbc_mkdispatch.py - do not")
    out.append(" * hand-edit. Maps an opcode to the index of the first rule in the")
    out.append(" * original if/else chain that matched it. 0xff = unknown opcode. */")
    out.append("static const unsigned char %s[256] = {" % name)
    for r in range(0, 256, 16):
        row = ", ".join("0x%02x" % v for v in table[r:r + 16])
        out.append("    %s," % row)
    out.append("};")
    out.append("")

    body = [prelude.rstrip()]
    body.append("    switch (%s[op]) {" % name)
    for n, (val, mask, b) in enumerate(entries):
        body.append("    case %d: { /* M(op, 0x%02x, 0x%02x) */" % (n, val, mask))
        body.append(b.rstrip())
        body.append("    } break;")
    body.append("    default: {")
    body.append((tail or '        cpu_error("Unknown instruction");').rstrip())
    body.append("    } break;")
    body.append("    }")

    return "\n".join(out), "\n".join(body)


def main():
    path = sys.argv[1]
    src = open(path).read()

    if "gbc_mkdispatch.py" in src:
        sys.exit("refusing to run: %s already converted" % path)

    for fn in CHAINS:
        b_open, b_close = find_body(src, fn)
        body = src[b_open + 1:b_close]

        prelude, entries, tail = split_chain(body)
        if not entries:
            sys.exit("no chain found in " + fn)

        table = build_table(entries)

        # Sanity: every opcode the original chain could handle must still map
        # to the same rule, and the bodies must be preserved verbatim.
        for op in range(256):
            expect = 0xFF
            for n, (val, mask, _) in enumerate(entries):
                if (op & mask) == val:
                    expect = n
                    break
            assert table[op] == expect, "table mismatch at 0x%02x" % op

        tbl_txt, new_body = emit(fn, prelude, entries, tail, table)

        for _, _, ob in entries:
            assert ob.strip() in new_body, "body lost during rewrite"

        src = src[:b_open + 1] + "\n" + new_body + "\n" + src[b_close:]
        # table goes immediately before the function
        anchor = "static void %s(struct gb_state *s) {" % fn
        src = src.replace(anchor, tbl_txt + "\n" + anchor, 1)

        covered = sum(1 for v in table if v != 0xFF)
        print("%-24s %d rules, %d/256 opcodes covered" % (fn, len(entries), covered))

    open(path, "w").write(src)
    print("wrote", path)


if __name__ == "__main__":
    main()
