#!/usr/bin/env python3
"""Emit a boot_image.h whose JPEG can be replaced on the card after the build.

Background
----------
Two different things were both called "the custom boot screen":

  * A480 - the image lives in a marker-tagged slot inside the *loader*
    (loader/a480/main.c), which the loader copies to RAM for the replacement
    StartupImage task to read. Nothing is compiled into the core, and the
    on-camera importer (modules/boot_image.c) rewrites the slot inside
    DISKBOOT.BIN.

  * A430 / A460 / A470 - the image was a plain `boot_image_jpeg[]` array
    compiled into the core. That works, but it is fixed at build time: there is
    nothing for the importer to find, so "Boot screen -> Import JPG/PNG" could
    not be offered on those bodies.

This tool emits the array in the *same* marker-tagged slot layout the A480
loader uses, so one importer serves every camera:

    struct {
        unsigned marker[4];              // "BOOTSLOT" <TAG> "IMG1"
        unsigned capacity;               // bytes of jpeg[] reserved
        unsigned size;                   // bytes of jpeg[] actually used
        unsigned char jpeg[capacity];    // padded with 0xff
    }

The marker is what the importer scans for, the size is what boot.c copies, and
the capacity is fixed so a replacement image never has to move anything.

The slot is deliberately non-const `volatile`: it must survive as real bytes in
main.bin for the importer to find and patch, so the compiler must not fold,
deduplicate or discard it. loader/a480/main.c declares its slot the same way and
is found in DISKBOOT.BIN exactly as intended.

Usage
-----
  mkbootslot.py --tag A430 --from-header old_boot_image.h -o boot_image.h
  mkbootslot.py --tag A430 --jpeg art.jpg -o boot_image.h

--from-header re-emits the bytes already in a generated header without
re-encoding them. That matters: these JPEGs must keep standard (not optimised)
Huffman tables and the stock marker layout or the firmware decoder renders a
black screen, and the existing headers are known-good in exactly that respect.
"""

import argparse
import os
import re
import sys

MAX_CAPACITY = 18426      # BOOT_SCREEN_MAX_JPEG, the length Canon declares


def bytes_from_header(path):
    text = open(path).read()
    start = text.index("boot_image_jpeg")
    open_brace = text.index("{", start)
    close_brace = text.index("};", open_brace)
    body = text[open_brace:close_brace]
    return bytes(int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]{2})", body))


def marker_words(tag):
    """The 16 marker bytes as four little-endian words.

    Spelled out as words rather than a string so the emitted initialiser is
    endian-explicit and matches what the importer compares against.
    """
    raw = b"BOOTSLOT" + tag.encode("ascii") + b"IMG1"
    if len(raw) != 16:
        sys.exit("tag must be exactly 4 ASCII characters, got %r" % tag)
    return [int.from_bytes(raw[i:i + 4], "little") for i in range(0, 16, 4)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", required=True,
                    help="4-character camera tag, e.g. A430")
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--from-header", help="re-emit an existing boot_image.h")
    src.add_argument("--jpeg", help="a ready 320x240 baseline JPEG")
    ap.add_argument("--capacity", type=int, default=MAX_CAPACITY,
                    help="bytes to reserve for jpeg[]. Defaults to the %d Canon "
                         "declares for its own buffer. Lower it only where the "
                         "core budget cannot afford the full slot - the A470 - "
                         "since it also caps what can later be imported."
                         % MAX_CAPACITY)
    ap.add_argument("-o", "--out", required=True)
    args = ap.parse_args()

    if args.from_header:
        data = bytes_from_header(args.from_header)
        origin = os.path.basename(args.from_header)
    else:
        data = open(args.jpeg, "rb").read()
        origin = os.path.basename(args.jpeg)

    # Generated headers are already padded to capacity with 0xff. Strip that
    # padding back off so `size` is the real JPEG length, then re-pad. Only
    # trailing 0xff after the EOI marker is padding; EOI itself is ff d9.
    end = data.rfind(b"\xff\xd9")
    if data[:2] != b"\xff\xd8" or end < 0:
        sys.exit("%s is not a JPEG (no SOI/EOI)" % origin)
    size = end + 2
    cap = args.capacity
    if not 4 <= cap <= MAX_CAPACITY:
        sys.exit("capacity must be between 4 and %d" % MAX_CAPACITY)
    if size > cap:
        sys.exit("image is %d bytes, over the %d byte slot" % (size, cap))
    data = data[:size] + b"\xff" * (cap - size)

    words = marker_words(args.tag)
    lines = [
        "// Generated by tools/mkbootslot.py from %s - DO NOT EDIT BY HAND." % origin,
        "//",
        "// A marker-tagged boot screen slot. The image is compiled in as the",
        "// default, and modules/boot_image.c can replace it on the card by",
        "// finding the marker inside DISKBOOT.BIN - which is what makes",
        "// Settings -> Boot screen -> Import JPG/PNG work on this body.",
        "//",
        "// 320x240 baseline JPEG, 4:2:0, JFIF, STANDARD Huffman tables. Optimised",
        "// tables render as a black screen - the firmware decoder only handles the",
        "// standard ones. Padded with 0xff after EOI to exactly %d bytes." % cap,
        "//",
        "// volatile, and not const, so the slot survives into main.bin as real",
        "// bytes for the importer to find. See tools/mkbootslot.py.",
        "",
        '#include "boot_screen.h"',
        "",
        "#define BOOT_IMAGE_SLOT_CAPACITY %d" % cap,
        "",
        "// Its own struct, not boot_image_slot_t: the jpeg[] length is this",
        "// camera's capacity rather than the shared maximum. Both layouts start",
        "// with the same marker/capacity/size fields, which is all the importer",
        "// and BOOT_IMAGE_SLOT_VALID() need.",
        "volatile struct {",
        "    unsigned marker[4];",
        "    unsigned capacity;",
        "    unsigned size;",
        "    unsigned char jpeg[BOOT_IMAGE_SLOT_CAPACITY];",
        "} boot_image_slot __attribute__((aligned(4))) = {",
        "    { 0x%08x, 0x%08x, 0x%08x, 0x%08x }," % tuple(words),
        "    BOOT_IMAGE_SLOT_CAPACITY,",
        "    %d," % size,
        "    {",
    ]
    for i in range(0, len(data), 16):
        lines.append("    " + "".join("0x%02x," % b for b in data[i:i + 16]))
    lines.extend(["    }", "};"])
    open(args.out, "w").write("\n".join(lines) + "\n")
    print("wrote %s: tag %s, %d bytes image + %d padding = %d capacity"
          % (args.out, args.tag, size, cap - size, cap))


if __name__ == "__main__":
    main()
