#!/usr/bin/env python3
"""
Build a replacement Canon boot screen for a CHDK camera.

Encodes an image to a JPEG the camera's firmware decoder will accept, and emits
it as a C header for embedding in platform/<cam>/sub/<fw>/boot.c.

Two things matter and are easy to get wrong:

  * STANDARD Huffman tables (optimize=False). PIL's optimised tables are smaller
    but the firmware decoder rejects them and displays a black screen.
  * The file must fit the buffer Canon allocates for its own logo. It is padded
    with 0xFF after EOI to exactly that length, so a decoder reading the declared
    size rather than stopping at EOI still gets what it expects.

Find --size by locating the stock JPEG in a ROM dump (see find_startup_image).

Usage:
  mkbootimg.py art.png --size 18426 -o boot_image.h
  mkbootimg.py --animation frame0.png frame1.png frame2.png --size 18426 \
      --total-size 18000 -o boot_animation.h
  mkbootimg.py --find-in PRIMARY.BIN            # locate candidate startup images
  mkbootimg.py --compare mine.jpg stock.jpg     # diff JPEG marker structure
"""

import argparse
import io
import re
import sys


def markers(d):
    """Marker structure of a JPEG, e.g. 'E0(16) DB(67) ... DA(12)'."""
    i, out = 2, []
    while i < len(d) - 1:
        if d[i] != 0xFF:
            i += 1
            continue
        m = d[i + 1]
        if m in (0xD8, 0xD9, 0x01) or 0xD0 <= m <= 0xD7:
            i += 2
            continue
        seg = int.from_bytes(d[i + 2:i + 4], "big")
        out.append("%02X(%d)" % (m, seg))
        if m == 0xDA:
            break
        i += 2 + seg
    return " ".join(out)


def find_in_rom(path, rombase=0xFFC00000):
    """List embedded JPEGs in a ROM dump - the startup image is the 320x240 one."""
    from PIL import Image
    d = open(path, "rb").read()
    print("%-12s %-9s %-12s %s" % ("ADDRESS", "BYTES", "SIZE", "MARKERS"))
    for m in re.finditer(rb"\xff\xd8\xff", d):
        s = m.start()
        e = d.find(b"\xff\xd9", s)
        if e < 0:
            continue
        blob = d[s:e + 2]
        try:
            im = Image.open(io.BytesIO(blob))
            dims = "%dx%d" % im.size
        except Exception:
            dims = "(not a jpeg)"
        print("%#010x  %-9d %-12s %s" % (rombase + s, len(blob), dims, markers(blob)))
    print("\nThe startup image is normally 320x240. Note its BYTES value - that is")
    print("--size, the buffer length Canon declares. Then find the single literal")
    print("reference to its address in the ROM to locate the My Camera init.")


def encode_image(src, limit, quality_hint=None):
    from PIL import Image

    im = Image.open(src).convert("RGB")
    w, h = im.size

    # centre-crop to 4:3, then scale to the panel size
    tw, th = 4, 3
    if w / h > tw / th:
        nw = int(h * tw / th)
        im = im.crop(((w - nw) // 2, 0, (w + nw) // 2, h))
    else:
        nh = int(w * th / tw)
        im = im.crop((0, (h - nh) // 2, w, (h + nh) // 2))
    im = im.resize((320, 240), Image.LANCZOS)

    qualities = [quality_hint] if quality_hint else range(90, 4, -1)
    data = None
    for q in qualities:
        buf = io.BytesIO()
        # optimize=False is required: standard Huffman tables only
        im.save(buf, "JPEG", quality=q, subsampling=2,
                progressive=False, optimize=False)
        if buf.tell() <= limit:
            data, chosen = buf.getvalue(), q
            break
    if data is None:
        sys.exit("could not fit %s into %d bytes even at lowest quality" % (src, limit))

    return data, chosen


def build(src, limit, out_path, var, quality_hint=None):
    data, chosen = encode_image(src, limit, quality_hint)
    pad = limit - len(data)
    data += b"\xff" * pad
    print("quality %d, %d bytes + %d padding = %d" % (chosen, len(data) - pad, pad, len(data)))
    print("markers: %s" % markers(data))

    lines = [
        "// Generated by tools/mkbootimg.py from %s - DO NOT EDIT BY HAND." % src,
        "// 320x240 baseline JPEG, 4:2:0, JFIF, standard Huffman tables.",
        "// Padded with 0xFF after EOI to exactly %d bytes, the length Canon" % limit,
        "// declares for its own startup image buffer.",
        "//",
        "// Verify against the stock image before trusting it:",
        "//   mkbootimg.py --compare <this>.jpg rom_assets/canon_startup.jpg",
        "",
        "static const unsigned char %s[] __attribute__((aligned(4))) = {" % var,
    ]
    for i in range(0, len(data), 16):
        lines.append("    " + "".join("0x%02x," % b for b in data[i:i + 16]))
    lines.append("};")
    open(out_path, "w").write("\n".join(lines) + "\n")
    print("wrote %s" % out_path)
    print("\nNOTE: the CHDK build does not track header dependencies -")
    print("      touch platform/<cam>/sub/<fw>/boot.c before rebuilding.")


def build_animation(sources, frame_limit, total_limit, out_path, quality_hint=None):
    if not sources:
        raise SystemExit("animation needs at least one frame")
    per_frame = min(frame_limit, total_limit // len(sources))
    encoded = []
    for source in sources:
        data, quality = encode_image(source, per_frame, quality_hint)
        encoded.append(data)
        print("%s: quality %d, %d bytes" % (source, quality, len(data)))
    total = sum(map(len, encoded))
    if total > total_limit:
        raise SystemExit("animation is %d bytes, above --total-size %d" %
                         (total, total_limit))

    lines = [
        "// Generated by tools/mkbootimg.py - DO NOT EDIT BY HAND.",
        "// Embedded Canon startup animation: %d frames, %d bytes total." %
        (len(encoded), total), "",
    ]
    for frame, data in enumerate(encoded):
        lines.append("static const unsigned char boot_anim_%d[] __attribute__((aligned(4))) = {" % frame)
        for i in range(0, len(data), 16):
            lines.append("    " + "".join("0x%02x," % b for b in data[i:i+16]))
        lines.append("};")
    lines.extend([
        "",
        "typedef struct { const unsigned char *data; unsigned size; } boot_anim_frame_t;",
        "static const boot_anim_frame_t boot_animation[] = {",
    ])
    for frame in range(len(encoded)):
        lines.append("    { boot_anim_%d, sizeof(boot_anim_%d) }," % (frame, frame))
    lines.extend(["};", ""])
    with open(out_path, "w") as output:
        output.write("\n".join(lines))
    print("wrote %s: %d frames, %d bytes total" % (out_path, len(encoded), total))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image", nargs="*")
    ap.add_argument("--size", type=int, help="Canon's buffer length, e.g. 18426")
    ap.add_argument("--quality", type=int, help="force a JPEG quality")
    ap.add_argument("--animation", action="store_true", help="emit an embedded frame table")
    ap.add_argument("--total-size", type=int, default=18000,
                    help="maximum total bytes for embedded animation")
    ap.add_argument("--var", default="boot_image_jpeg")
    ap.add_argument("-o", "--output", default="boot_image.h")
    ap.add_argument("--find-in", metavar="ROM")
    ap.add_argument("--compare", nargs=2, metavar=("A", "B"))
    a = ap.parse_args()

    if a.find_in:
        find_in_rom(a.find_in)
    elif a.compare:
        for p in a.compare:
            d = open(p, "rb").read()
            print("%-40s %6d  %s" % (p, len(d), markers(d)))
        ma, mb = (markers(open(p, "rb").read()) for p in a.compare)
        print("MATCH" if ma == mb else "DIFFERENT - decoder may reject the first")
    elif a.image and a.size and a.animation:
        build_animation(a.image, a.size, a.total_size, a.output, a.quality)
    elif len(a.image) == 1 and a.size:
        build(a.image[0], a.size, a.output, a.var, a.quality)
    else:
        ap.error("need an image plus --size, or --find-in / --compare")


if __name__ == "__main__":
    main()
