#ifndef BOOT_SCREEN_H
#define BOOT_SCREEN_H

#define BOOT_SCREEN_WIDTH    320
#define BOOT_SCREEN_HEIGHT   240
// The largest slot any camera here carries. Individual slots may be smaller -
// see `capacity` below - so this is a bound for buffers, not the slot size.
#define BOOT_SCREEN_MAX_JPEG 18426

// The custom boot screen slot.
//
// One layout serves two different delivery routes, so that a single on-camera
// importer (modules/boot_image.c) can replace the image on every body that has
// one:
//
//   A480          the slot lives in the *loader* (loader/a480/main.c), which
//                 copies it to a fixed RAM address for the replacement
//                 StartupImage task to read. Nothing is compiled into the core.
//
//   A430/A460/    the slot is compiled into the core as the default image
//   A470          (sub/<fw>/boot_image.h, generated by tools/mkbootslot.py) and
//                 read directly by that body's startup-image hook.
//
// Either way the bytes end up inside DISKBOOT.BIN, and the importer finds them
// by scanning for the 16-byte marker rather than by knowing any offset. The
// capacity is fixed so a replacement never has to move anything after it.
//
// `capacity` is how many bytes of jpeg[] the slot actually reserves and
// `size` how many of them the current image uses; the remainder is 0xff
// padding. A slot whose size is 0 (or whose jpeg does not start with an SOI)
// has never been written and the caller must leave Canon's own image alone.
//
// The capacity is stored rather than fixed because the slot competes for the
// same fixed core budget as the rest of CHDK, and that budget is tighter on
// some bodies than others. The A470 in particular cannot afford a full
// 18426-byte slot: padding it to that size put its core 256 bytes over the
// 200 KB ceiling. Storing the capacity lets each camera reserve what it can
// afford, and lets one importer patch any of them without a table of sizes.
typedef struct {
    unsigned marker[4];
    unsigned capacity;
    unsigned size;
    unsigned char jpeg[BOOT_SCREEN_MAX_JPEG];
} boot_image_slot_t;

// "BOOTSLOT" <4-char camera tag> "IMG1", as four little-endian words.
// 0x544f4f42 0x544f4c53 = "BOOT" "SLOT"; 0x31474d49 = "IMG1".
#define EARLY_BOOT_MARKER_0 0x544f4f42u
#define EARLY_BOOT_MARKER_1 0x544f4c53u
#define EARLY_BOOT_MARKER_3 0x31474d49u

// Per-camera third word: the tag, little-endian. "A480" -> 0x30383441.
#define BOOT_TAG_A430       0x30333441u
#define BOOT_TAG_A460       0x30363441u
#define BOOT_TAG_A470       0x30373441u
#define BOOT_TAG_A480       0x30383441u

// Kept for loader/a480/main.c and platform/a480/sub/100b/boot.c, which were
// written against the A480-only spelling.
#define EARLY_BOOT_MARKER_2 BOOT_TAG_A480

// True when the slot holds an image worth drawing.
//
// Checked rather than assumed because a boot.c that gets this wrong overwrites
// Canon's buffer with rubbish and shows a black screen with no way back except
// pulling the card. Every term matters:
//
//   marker    the slot is the one this camera's importer writes. The tag is
//             per-camera so an image imported for another body - or a stale
//             DISKBOOT.BIN - is ignored rather than drawn.
//   size      within the slot's own capacity. The caller copies `size` bytes,
//             not the whole capacity.
//   SOI/EOI   the firmware decoder is handed this directly, so something that
//             is not a JPEG at all is worth catching here. Both ends are
//             checked, not just the start, and that matters more than it
//             looks: on the A480 the slot is staged in RAM by the loader, and
//             if anything overwrites that staging area the marker and SOI at
//             the front can still survive while the body is gone. A front-only
//             test passes that and hands the decoder rubbish, which renders as
//             a black screen with no way back except pulling the card. Testing
//             the EOI at `size` makes that failure fall back to Canon's own
//             logo instead.
//
// A macro rather than a function because the compiled-in slots each declare
// their own struct with their own jpeg[] length - see tools/mkbootslot.py -
// and only the A480's RAM-staged copy uses boot_image_slot_t itself.
//
// A freshly built slot that has never been imported into still passes, because
// mkbootslot.py writes a real image and a real size as the compiled-in default.
#define BOOT_IMAGE_SLOT_VALID(s, tag)                    \
    ((s).marker[0] == EARLY_BOOT_MARKER_0 &&             \
     (s).marker[1] == EARLY_BOOT_MARKER_1 &&             \
     (s).marker[2] == (unsigned)(tag) &&                 \
     (s).marker[3] == EARLY_BOOT_MARKER_3 &&             \
     (s).capacity >= 4 &&                                \
     (s).capacity <= BOOT_SCREEN_MAX_JPEG &&             \
     (s).size >= 4 && (s).size <= (s).capacity &&        \
     (s).jpeg[0] == 0xff && (s).jpeg[1] == 0xd8 &&       \
     (s).jpeg[(s).size - 2] == 0xff &&                   \
     (s).jpeg[(s).size - 1] == 0xd9)

#endif
